Repository DockYard/ember-router-scroll, pull requests merged in 2020-02, with the labels that each got.

#237 Remove recursive scroll check
  addon/index.js
  addon/utils/scrollbar-width.js
Labels: bug

#238 Upgrade ember-app-scheduler to v4.0.0
  README.md
  addon/index.js
  addon/services/router-scroll.js
  package.json
  tests/unit/router-scroll-test.js
  yarn.lock
Labels: dependencies, enhancement

#239 Scroll when afterRender
  README.md
  addon/index.js
  addon/services/router-scroll.js
  tests/unit/router-scroll-test.js
Labels: enhancement

#240 Missing setter for scrollWhenAfterRender
  addon/services/router-scroll.js
Labels: bug

#241 Prevent multiple calls on routeDidChange
  addon/index.js
Labels: bug

#243 [BUG] Ensure scheduleOnce runs once - v2
  addon/index.js
Labels: bug

#242 [BUG] update scroll position should only be called once
  CHANGELOG.md
  addon/index.js
Labels: bug

#244 [ENHANCEMENT] Bring back scroll recursive
  addon/index.js
Labels: enhancement
